### ISSUE TITLE
jboss/keycloak-mongo Failed to connect to database

### ISSUE THREAD

**Issue by techgaun** [jboss-dockerfiles/keycloak#35]
Trying to use https://github.com/jboss-dockerfiles/keycloak/tree/master/server-mongo , it just gives me error:
```
21:35:42,014 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 63) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.RuntimeException: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:160)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2211)
	at org.jboss.resteasy.spi.ResteasyDeployment.createApplication(ResteasyDeployment.java:295)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:236)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:112)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:230)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:131)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:511)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more
Caused by: java.lang.RuntimeException: Failed to connect to database
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:207)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.lazyInit(DefaultJpaConnectionProviderFactory.java:128)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:40)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.create(DefaultJpaConnectionProviderFactory.java:28)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:103)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProviderFactory.create(JpaUserSessionPersisterProviderFactory.java:21)
	at org.keycloak.models.jpa.session.JpaUserSessionPersisterProviderFactory.create(JpaUserSessionPersisterProviderFactory.java:15)
	at org.keycloak.services.DefaultKeycloakSession.getProvider(DefaultKeycloakSession.java:103)
	at org.keycloak.models.sessions.infinispan.initializer.OfflineUserSessionLoader.init(OfflineUserSessionLoader.java:20)
	at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer$1.run(InfinispanUserSessionInitializer.java:100)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:244)
	at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.getOrCreateInitializerState(InfinispanUserSessionInitializer.java:97)
	at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.startLoading(InfinispanUserSessionInitializer.java:148)
	at org.keycloak.models.sessions.infinispan.initializer.InfinispanUserSessionInitializer.loadPersistentSessions(InfinispanUserSessionInitializer.java:78)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$3.run(InfinispanUserSessionProviderFactory.java:111)
	at org.keycloak.models.utils.KeycloakModelUtils.runJobInTransaction(KeycloakModelUtils.java:244)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory.loadPersistentSessions(InfinispanUserSessionProviderFactory.java:102)
	at org.keycloak.models.sessions.infinispan.InfinispanUserSessionProviderFactory$2.onEvent(InfinispanUserSessionProviderFactory.java:86)
	at org.keycloak.services.DefaultKeycloakSessionFactory.publish(DefaultKeycloakSessionFactory.java:47)
	at org.keycloak.services.resources.KeycloakApplication.<init>(KeycloakApplication.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.jboss.resteasy.core.ConstructorInjectorImpl.construct(ConstructorInjectorImpl.java:148)
	... 19 more
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)
	at org.keycloak.connections.jpa.DefaultJpaConnectionProviderFactory.getConnection(DefaultJpaConnectionProviderFactory.java:203)
	... 43 more

21:35:42,020 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "keycloak-server.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./auth" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)
    Caused by: java.lang.RuntimeException: Failed to connect to database
    Caused by: java.lang.NullPointerException"}}
21:35:42,057 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 57) WFLYSRV0010: Deployed "keycloak-server.war" (runtime-name : "keycloak-server.war")
21:35:42,059 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./auth: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./auth: java.lang.RuntimeException: Failed to construct public org.keycloak.services.resources.KeycloakApplication(javax.servlet.ServletContext,org.jboss.resteasy.core.Dispatcher)

21:35:42,227 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
21:35:42,227 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0051: Admin console listening on http://127.0.0.1:9990
21:35:42,227 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: Keycloak 1.6.1.Final (WildFly Core 1.0.1.Final) started (with errors) in 3017ms - Started 305 of 527 services (2 services failed or missing dependencies, 274 services are lazy, passive or on-demand)
```

I entered the container and can see following environment variables:
```
MONGO_1_PORT_27017_TCP_ADDR=172.17.0.11
MONGO_ENV_MONGO_MAJOR=3.0
HOSTNAME=42c87ce29c70
MONGO_1_ENV_MONGO_VERSION=3.0.7
MONGO_1_PORT_27017_TCP=tcp://172.17.0.11:27017
MONGO_1_PORT=tcp://172.17.0.11:27017
KEYCLOAK_MONGO_1_ENV_MONGO_VERSION=3.0.7
MONGO_1_ENV_MONGO_MAJOR=3.0
MONGO_1_PORT_27017_TCP_PROTO=tcp
LAUNCH_JBOSS_IN_BACKGROUND=1
KEYCLOAK_MONGO_1_PORT_27017_TCP_ADDR=172.17.0.11
KEYCLOAK_MONGO_1_PORT_27017_TCP_PROTO=tcp
MONGO_PORT=tcp://172.17.0.11:27017
KEYCLOAK_MONGO_1_NAME=/keycloak_keycloak_1/keycloak_mongo_1
JBOSS_HOME=/opt/jboss/keycloak
MONGO_ENV_MONGO_VERSION=3.0.7
MONGO_PORT_27017_TCP=tcp://172.17.0.11:27017
MONGO_1_ENV_MONGODB_DBNAME=keycloak
LS_COLORS=
KEYCLOAK_MONGO_1_ENV_MONGO_MAJOR=3.0
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MONGO_1_PORT_27017_TCP_PORT=27017
KEYCLOAK_MONGO_1_PORT_27017_TCP=tcp://172.17.0.11:27017
KEYCLOAK_MONGO_1_PORT=tcp://172.17.0.11:27017
PWD=/opt/jboss
JAVA_HOME=/usr/lib/jvm/java
MONGO_PORT_27017_TCP_PROTO=tcp
KEYCLOAK_VERSION=1.6.1.Final
SHLVL=1
HOME=/opt/jboss
MONGO_ENV_MONGODB_DBNAME=keycloak
MONGO_1_NAME=/keycloak_keycloak_1/mongo_1
MONGO_PORT_27017_TCP_ADDR=172.17.0.11
affinity:container==d304843896d19664f2a9ce1ad75b05408a7f2dfcf17d373499bf3b3cfcd4cbb6
MONGODB_DBNAME=keycloak
LESSOPEN=||/usr/bin/lesspipe.sh %s
KEYCLOAK_MONGO_1_ENV_MONGODB_DBNAME=keycloak
KEYCLOAK_MONGO_1_PORT_27017_TCP_PORT=27017
MONGO_NAME=/keycloak_keycloak_1/mongo
MONGO_PORT_27017_TCP_PORT=27017
```

This looks good to me. However, I could not get `jboss/keycloak-mongo` working by following the readme. I however can see `keycloak` db being created with the following collections (which again is as expected):
```
clients
databaseChangeLog
migrationModel
realms
roles
system.indexes
userConsents
users
```

**Comment by tajakobsen** [comment]
This bug also affects Keycloak 1.7.0.Final (WildFly Core 1.0.2.Final)
